CREATE TABLE IF NOT EXISTS `vendors` (
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(255) NOT NULL,
    `category` VARCHAR(50) NOT NULL,
    `description` TEXT NULL,
    `lat` DECIMAL(10, 8) NOT NULL,
    `lng` DECIMAL(11, 8) NOT NULL,
    `address` TEXT NOT NULL,
    `phone` VARCHAR(20) NULL,
    `email` VARCHAR(255) NULL,
    `photos` JSON NULL,
    `languages` JSON NULL,
    `price_items` JSON NOT NULL,
    `trust_score` DECIMAL(3, 2) DEFAULT 0.00,
    `badges` JSON NULL,
    `verified` TINYINT(1) DEFAULT 0,
    `verified_by` INT UNSIGNED NULL,
    `verified_at` DATETIME NULL,
    `last_verified_date` DATE NULL,
    `verified_reviews_count` INT UNSIGNED DEFAULT 0,
    `total_reviews` INT UNSIGNED DEFAULT 0,
    `status` ENUM('active', 'inactive', 'suspended') DEFAULT 'active',
    `created_at` DATETIME NOT NULL,
    `updated_at` DATETIME NOT NULL,
    PRIMARY KEY (`id`),
    INDEX `idx_category` (`category`),
    INDEX `idx_verified` (`verified`),
    INDEX `idx_status` (`status`),
    INDEX `idx_location` (`lat`, `lng`),
    FOREIGN KEY (`verified_by`) REFERENCES `users`(`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

